hotkeys:
  shell: {}
  profile:
    cmd-clink: []
    wsl-default-distro: []
    wsl-ubuntu: []
  toggle-window: []
  paste:
    - - Ctrl-Shift-V
  new-tab: []
  close-tab: []
  next-tab:
    - - Ctrl-Tab
  previous-tab:
    - - Ctrl-Shift-Tab
  zoom-in:
    - - Ctrl-=
    - - Ctrl-Shift-=
terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  font: Ricty Diminished Regular
  fontSize: 14
  background: theme
  environment: {}
  profile: wsl-ubuntu
  ligatures: false
  rightClick: menu
  profiles: []
  autoOpen: true
  workingDirectory: 'C:\Users\yoshio\home'
ssh: {}
appearance:
  vibrancyType: fluent
  theme: Compact
  opacity: 0.74
  css: '/* * { color: blue !important; } */'
  tabsLocation: top
  vibrancy: false
  frame: thin
  dock: 'off'
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []
